{% set name = "sagemaker-studio" %}
{% set version = "1.1.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sagemaker_studio-{{ version }}.tar.gz
  sha256: 9c5ec7b5d910331493f7188a7aef50c2d19e4b0e20cc820343355c32e0f496ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - mypy
    - invoke
    - pip
  run:
    - python >={{ python_min }}
    - boto3 >=1.34.106
    - botocore >=1.34.106
    - urllib3 >=1.26.19
    - requests >=2.25.1
    - psutil >=5.9.8
    - python-dateutil >=2.5.3
    - setuptools >=21.0.0
    - packaging >=24.0
    - pyathena >=3.18.0
    - sqlalchemy >=2.0.43
    - pandas >=2.3.2
    - duckdb >=1.4.0
    - awswrangler >=3.5.0
    - pyiceberg >=0.7.0
    - numpy >=1.26.4,<2.3.0
    - pyarrow >=19.0.0
    - psycopg2-binary >=2.9.10
    - pymysql >=1.1.2
    - snowflake-sqlalchemy >=1.7.7
    - sqlalchemy-bigquery >=0.0.7
    - pymssql >=2.3.8
    - aws-embedded-metrics >=3.3.0

test:
  imports:
    - sagemaker_studio
  commands:
    - pip install pydynamodb
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker/
  summary: Python library to interact with Amazon SageMaker Unified Studio
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bharathGuntamadugu
    - nwangamz
    - tejaskash
    - devanshdesai
    - akashg105
