{% set name = "sagemaker-studio" %}
{% set version = "1.0.15" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sagemaker_studio-{{ version }}.tar.gz
  sha256: 193ed3262a17be20c3312da2ad96b45d83103d0b582a9ec5c2a3ebd8e803817e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - mypy
    - invoke
    - pip
  run:
    - python >={{ python_min }}
    - boto3 >=1.34.106
    - botocore >=1.34.106
    - urllib3 >=1.26.19
    - requests >=2.25.1
    - psutil >=5.9.8
    - python-dateutil >=2.5.3
    - setuptools >=21.0.0
    - packaging >=24.0

test:
  imports:
    - sagemaker_studio
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker/
  summary: Python library to interact with Amazon SageMaker Unified Studio
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nwangamz
    - tejaskash
    - devanshdesai
    - akashg105
